development:
  dialect: postgres
  database: rancher-wrangler_development
  user: postgres
  password: postgres
  host: localhost
  port: 32768
  pool: 5

test:
  dialect: postgres
  database: rancher-wrangler_test
  user: postgres
  password: postgres
  host: localhost
  port: 32768

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/rancher-wrangler_production"}}