development:
  dialect: postgres
  database: rancher-wrangler_development
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5

test:
  dialect: postgres
  database: rancher-wrangler_test
  user: postgres
  password: postgres
  host: localhost
  port: 5432

